//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序集：{0}的Config标签没有设置ConfigType属性.
        /// </summary>
        internal static string ConfigNoType {
            get {
                return ResourceManager.GetString("ConfigNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒：Kiss.config里没有找到节点：{0}.
        /// </summary>
        internal static string FindNoNode {
            get {
                return ResourceManager.GetString("FindNoNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.config/web.config没有找到Kiss节点.
        /// </summary>
        internal static string KissConfigIsNull {
            get {
                return ResourceManager.GetString("KissConfigIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载Provider失败。.
        /// </summary>
        internal static string LoadProviderFailed {
            get {
                return ResourceManager.GetString("LoadProviderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序集：{0}上没有加上Config标签.
        /// </summary>
        internal static string NoConfigInAssembly {
            get {
                return ResourceManager.GetString("NoConfigInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型：{0} 没有加上ConfigNode标签.
        /// </summary>
        internal static string NoConfigNodeAttribute {
            get {
                return ResourceManager.GetString("NoConfigNodeAttribute", resourceCulture);
            }
        }
    }
}
